/*
 * Launch config for standalone deployment.
 * Generated by scripts/set-launch-config.ps1
 */
window.LAUNCH_CONFIG = {
  canonicalUrl: 'https://swp1234.github.io/road-shooter/',
  ogImageUrl: 'https://swp1234.github.io/road-shooter/icon-512.svg',
  enableAds: true,
  adsenseClient: 'ca-pub-3600813755953882',
  enableAnalytics: true,
  gaMeasurementId: 'G-J8GSWM40TV',
  enableCrossPromo: false,
  crossPromoScriptUrl: ''
};
