param(
  [string]$CanonicalUrl = "",
  [string]$OgImageUrl = "",
  [string]$AdsenseClient = "",
  [string]$GaMeasurementId = "",
  [string]$CrossPromoScriptUrl = "",
  [switch]$EnableAds,
  [switch]$EnableAnalytics,
  [switch]$EnableCrossPromo
)

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$target = Join-Path $root "js\shared\launch-config.js"

function Escape-JsString([string]$value) {
  if ($null -eq $value) { return "" }
  return $value.Replace("\", "\\").Replace("'", "\'")
}

$adsEnabled = $EnableAds.IsPresent -or -not [string]::IsNullOrWhiteSpace($AdsenseClient)
$analyticsEnabled = $EnableAnalytics.IsPresent -or -not [string]::IsNullOrWhiteSpace($GaMeasurementId)
$crossPromoEnabled = $EnableCrossPromo.IsPresent -or -not [string]::IsNullOrWhiteSpace($CrossPromoScriptUrl)

$content = @"
/*
 * Launch config for standalone deployment.
 * Generated by scripts/set-launch-config.ps1
 */
window.LAUNCH_CONFIG = {
  canonicalUrl: '$(Escape-JsString $CanonicalUrl)',
  ogImageUrl: '$(Escape-JsString $OgImageUrl)',
  enableAds: $($adsEnabled.ToString().ToLower()),
  adsenseClient: '$(Escape-JsString $AdsenseClient)',
  enableAnalytics: $($analyticsEnabled.ToString().ToLower()),
  gaMeasurementId: '$(Escape-JsString $GaMeasurementId)',
  enableCrossPromo: $($crossPromoEnabled.ToString().ToLower()),
  crossPromoScriptUrl: '$(Escape-JsString $CrossPromoScriptUrl)'
};
"@

Set-Content -Path $target -Value $content -Encoding UTF8
Write-Host "Updated launch config:"
Write-Host $target
